/* SPDX-License-Identifier: GPL-2.0-or-later */

#include QMK_KEYBOARD_H

#include "peppy.h"
#include "g/keymap_combo.h"

// clang-format off
#define LAYOUT_wrapper(...) LAYOUT(__VA_ARGS__)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[0] = LAYOUT_wrapper(
		KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSLS, KC_GRV,
		KC_TAB, ___LEFT_BASE_ROW2___, XXXX, ___RGHT_BASE_ROW2___, KC_LBRC, KC_RBRC,
		KC_LGUI, ___LEFT_BASE_ROW3___, XXXX, ___RGHT_BASE_ROW3___, KC_SCLN,
		KC_LSFT, ___LEFT_BASE_ROW4___, XXXX, ___RGHT_BASE_ROW4___, KC_SLSH,
		KC_LCTL, KC_LGUI, KC_LALT, NAV_SPC, XXXX, KC_RALT, KC_RGUI, KC_RCTL
	),

	[1] = LAYOUT_wrapper(
		XXXX, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  XXXX, KC_DEL,
		XXXX, ___LEFT_NAV_ROW2___, XXXX, ___RGHT_NAV_ROW2___, XXXX, XXXX,
		XXXX, ___LEFT_NAV_ROW3___, XXXX, ___RGHT_NAV_ROW3___, XXXX,
		XXXX, ___LEFT_NAV_ROW4___, XXXX, ___RGHT_NAV_ROW4___, XXXX,
		XXXX, XXXX, XXXX, VVVV, XXXX, XXXX, XXXX, XXXX
	),

	[2] = LAYOUT_wrapper(
		XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX,
		XXXX, ___LEFT_SYM_ROW2___, XXXX, ___RGHT_SYM_ROW2___, XXXX, XXXX,
		XXXX, ___LEFT_SYM_ROW3___, XXXX, ___RGHT_SYM_ROW3___, XXXX,
		XXXX, ___LEFT_SYM_ROW4___, XXXX, ___RGHT_SYM_ROW4___, XXXX,
		XXXX, XXXX, XXXX, VVVV, XXXX, XXXX, XXXX, XXXX
	),

	[3] = LAYOUT_wrapper(
		XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX,
		XXXX, ___LEFT_NUM_ROW2___, XXXX, ___RGHT_NUM_ROW2___, XXXX, XXXX,
		XXXX, ___LEFT_NUM_ROW3___, XXXX, ___RGHT_NUM_ROW3___, XXXX,
		XXXX, ___LEFT_NUM_ROW4___, XXXX, ___RGHT_NUM_ROW4___, XXXX,
		XXXX, XXXX, XXXX, VVVV, XXXX, XXXX, XXXX, XXXX
	),

};
